version: '3.9'

services:
    app:
        build: ./badcat/apache
        image: badcat-app
        container_name: badcat-app
        ports:
            - '8080:80'
        volumes:
            - ./src:/var/www/html
        privileged: true
        depends_on:
            - db

    db:
        build: ./badcat/db
        image: badcat-db
        container_name: badcat-db
        environment:
            - MYSQL_ROOT_PASSWORD:root
            - MYSQL_DATABASE:badcat_db
            - MYSQL_USER:badcat_user
            - MYSQL_PASSWORD:badcat_pswd
            - TZ:'Asia/Tokyo'
        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        volumes:
            - ./badcat/db/data:/var/lib/mysql
        ports:
            - '3306:330'

